# configuring environment
env = Environment(
	CCFLAGS = '-Wall -pedantic',
	LIBPATH = '/usr/lib',
	LIBS = ['boost_thread', 'boost_system'],
)

# defining source files list
main = [ 'main.cpp' ]
core = [
  'ClientAuthenticator.cpp',
  'CommandExecutor.cpp',
  'ConnectionHandler.cpp',
  'Server.cpp',
  '../common/MessageDictionary.cpp',
  '../common/MD5.cpp'
]

# defining application ingredients
app = core
program = env.Program(target = 'server', source = app + main)
Default(program)
